(function(root){"use strict";
const DAY=86400000,p=v=>String(v).padStart(2,"0");
function localDateString(d=new Date()){return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`}
function parseLocalDate(v){const[y,m,d]=v.split("-").map(Number);return new Date(y,m-1,d,12)}
function addDays(v,n){const d=parseLocalDate(v);d.setDate(d.getDate()+n);return localDateString(d)}
function daysBetween(a,b){return Math.round((parseLocalDate(b)-parseLocalDate(a))/DAY)}
function checkinSchedule(startDate,checkins,today=localDateString()){const latest=checkins.at(-1),anchor=latest?.date||startDate,nextDate=addDays(anchor,14),daysToGo=daysBetween(today,nextDate);return{anchor,nextDate,daysToGo,due:daysToGo<=0}}
function weekBounds(v,start=0){const d=parseLocalDate(v),distance=(d.getDay()-Number(start)+7)%7,s=addDays(v,-distance);return{start:s,end:addDays(s,6)}}
function num(v){if(v===""||v==null)return null;const n=Number(v);return Number.isFinite(n)?n:null}
const sum=a=>a.reduce((t,v)=>t+(num(v)??0),0);
function average(a){const x=a.map(num).filter(v=>v!==null);return x.length?sum(x)/x.length:null}
function weeklyBudget(logs,s,date){const b=weekBounds(date,s.weekStart),w=logs.filter(l=>l.date>=b.start&&l.date<=b.end),consumed=sum(w.map(l=>l.calories)),budget=num(s.weeklyCalories)??0,remaining=budget-consumed,remainingDays=Math.max(0,daysBetween(date,b.end));return{...b,budget,consumed,remaining,remainingDays,perDay:remainingDays?remaining/remainingDays:remaining}}
function groupWeeks(logs,s,today=localDateString()){const map=new Map;logs.forEach(l=>{const b=weekBounds(l.date,s.weekStart);if(!map.has(b.start))map.set(b.start,{...b,logs:[]});map.get(b.start).logs.push(l)});return[...map.values()].sort((a,b)=>b.start.localeCompare(a.start)).map(w=>({...w,complete:w.end<today,daysLogged:new Set(w.logs.map(l=>l.date)).size,averageWeight:average(w.logs.map(l=>l.weight)),averageCalories:average(w.logs.map(l=>l.calories)),totalCalories:sum(w.logs.map(l=>l.calories)),averageProtein:average(w.logs.map(l=>l.protein)),averageSteps:average(w.logs.map(l=>l.steps)),liftingDays:w.logs.filter(l=>l.lifted).length})).map((w,i,a)=>{const prev=a[i+1],change=w.complete&&prev?.complete&&w.averageWeight!=null&&prev.averageWeight!=null?w.averageWeight-prev.averageWeight:null,loss=change==null?null:-change;let pace="In progress";if(loss!=null)pace=loss<Number(s.lossMin||0)?"Slower":loss>Number(s.lossMax||0)?"Faster":"On target";return{...w,change,loss,pace,calorieBalance:Number(s.weeklyCalories||0)-w.totalCalories}})}
function checkpointProgress(s,current){const start=num(s.startingWeight),goal=num(s.checkpointWeight),now=num(current);if([start,goal,now].some(v=>v==null))return null;const down=goal<=start,total=Math.abs(goal-start),moved=down?start-now:now-start;return{lost:down?start-now:now-start,remaining:down?now-goal:goal-now,percent:total?Math.max(0,Math.min(100,moved/total*100)):100,reached:down?now<=goal:now>=goal}}
const api={localDateString,parseLocalDate,addDays,daysBetween,checkinSchedule,weekBounds,num,sum,average,weeklyBudget,groupWeeks,checkpointProgress};root.TrackerUtils=api;if(typeof module!=="undefined")module.exports=api})(globalThis);
